### ISSUE TITLE
entityManagerFactory 中的packages确定写对了吗？

### ISSUE THREAD

**Issue by bodekjan** [weisenzcharles/WeiNote#1]
CustomerConfig.class 34行的:
return builder.dataSource(dataSource).packages("com.springboot.jpa.customer.data").persistenceUnit("customer").build();
这段中确定是com.springboot.jpa.customer.data吗？不是com.springboot.jpa.customer.models？

**Comment by weisenzcharles** [comment]
是的，修复了哈
